-- =============================================================
-- B9: Baseline Migration — Brilliant Jobs Schema
-- Date: 2026-02-19  |  Fixed: 2026-02-23
-- Purpose: Complete schema for Supabase Preview branches
-- WARNING: This is a BASELINE — do not run on the production database.
--          It exists for preview branches and new environment setup.
-- =============================================================

-- ─── EXTENSIONS ────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ─── COHORTS TABLE ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cohorts (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text,
  parent_cohort_id text,
  criteria_type text NOT NULL,
  criteria_value jsonb NOT NULL DEFAULT '{}'::jsonb,
  pricing_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  is_locked boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ─── PROFILES TABLE ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  email text,
  linkedin_slug text,
  linkedin_url text,
  sharing_enabled boolean DEFAULT false,
  last_scan_at timestamptz,
  created_at timestamptz DEFAULT now(),
  approved boolean DEFAULT false,
  approved_at timestamptz,
  email_optin boolean DEFAULT false,
  scanner_today_visited integer DEFAULT 0,
  scanner_today_limit integer DEFAULT 0,
  scanner_today_date text,
  scanner_next_resume_at timestamptz,
  scanner_running boolean DEFAULT false,
  full_name text,
  signup_elapsed_seconds integer,
  validation_result jsonb,
  last_seen_at timestamptz,
  user_data jsonb DEFAULT '{}'::jsonb,
  role text DEFAULT 'user'::text,
  plan text DEFAULT 'free'::text,
  deleted_at timestamptz,
  cohort_id text REFERENCES cohorts(id),
  cohort_assigned_at timestamptz
);

-- ─── ATS_COMPANIES TABLE ──────────────────────────────────
CREATE TABLE IF NOT EXISTS ats_companies (
  slug text NOT NULL,
  name text NOT NULL,
  job_count integer DEFAULT 0,
  source text NOT NULL DEFAULT 'greenhouse'::text,
  last_checked timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  industry text,
  website text,
  linkedin_url text,
  employee_size text,
  locality text,
  region text,
  country text,
  founded integer,
  ref_company_id integer,
  is_active boolean DEFAULT true,
  last_http_status integer,
  last_refresh_at timestamptz,
  PRIMARY KEY (slug, source)
);

-- ─── ATS_JOBS TABLE ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ats_jobs (
  greenhouse_id text NOT NULL,
  company_slug text,
  company_name text,
  title text NOT NULL,
  location text,
  department text,
  url text,
  updated_at timestamptz,
  last_seen timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  content text,
  first_seen_at timestamptz DEFAULT now(),
  lat double precision,
  lng double precision,
  location_normalized text,
  is_remote boolean DEFAULT false,
  status text DEFAULT 'open'::text,
  closed_at timestamptz,
  salary_min integer,
  salary_max integer,
  salary_raw text,
  loc_city text,
  loc_state text,
  loc_country text,
  loc_type text,
  loc_display text,
  loc_multi boolean DEFAULT false,
  search_vector tsvector,
  job_lat double precision,
  job_lng double precision,
  salary_currency text DEFAULT 'USD'::text,
  salary_rate text DEFAULT 'yr'::text,
  industry text,
  ats_source text DEFAULT 'greenhouse'::text,
  job_cat text
);

CREATE UNIQUE INDEX IF NOT EXISTS ats_jobs_source_id_unique ON ats_jobs (greenhouse_id, ats_source);

-- ─── CONNECTIONS TABLE ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS connections (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  profile_slug text NOT NULL UNIQUE,
  name text,
  headline text,
  parsed_company text,
  source text DEFAULT 'connections'::text,
  collected_at timestamptz DEFAULT now(),
  visit_status text DEFAULT 'pending'::text,
  visited_at timestamptz,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE,
  hiring_signal text,
  deleted_at timestamptz
);

-- ─── RESUMES TABLE ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS resumes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  name text NOT NULL,
  file_name text NOT NULL,
  file_path text,
  file_size text,
  is_default boolean DEFAULT false,
  level_label text,
  level_color text,
  needs_upload boolean DEFAULT false,
  source text DEFAULT 'upload'::text,
  created_at timestamptz DEFAULT now(),
  deleted_at timestamptz
);

-- ─── NOTIFICATION_LOG TABLE ────────────────────────────────
CREATE TABLE IF NOT EXISTS notification_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE SET NULL,
  notification_type text NOT NULL,
  channel text NOT NULL,
  status text DEFAULT 'sent'::text,
  job_id text,
  company_name text,
  subject text,
  payload jsonb,
  created_at timestamptz DEFAULT now(),
  idempotency_key text,
  user_plan text,
  user_cohort text,
  template_version text
);

-- ─── NOTIFICATION_ACTIONS TABLE ────────────────────────────
CREATE TABLE IF NOT EXISTS notification_actions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE SET NULL,
  job_id text NOT NULL,
  company_name text,
  job_title text,
  filter_name text,
  resume_id text,
  action_type text DEFAULT 'apply_decision'::text,
  status text DEFAULT 'pending'::text,
  email_sent_at timestamptz,
  sms_sent_at timestamptz,
  responded_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now(),
  credits_used integer DEFAULT 0,
  notification_tier text,
  decision text,
  response_channel text,
  CONSTRAINT unique_user_job_action UNIQUE (user_id, job_id, action_type)
);

-- ─── FEEDBACK TABLE ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feedback (
  id serial PRIMARY KEY,
  type text NOT NULL,
  user_id uuid REFERENCES auth.users ON DELETE SET NULL,
  page text,
  created_at timestamptz DEFAULT now(),
  title text,
  details text,
  severity text,
  screenshot_urls text[],
  survey_version text,
  answers jsonb,
  uninstall_reason text,
  overall_rating smallint,
  status text DEFAULT 'new'::text,
  admin_notes text,
  resolved_at timestamptz,
  feature_context text,
  nps_score smallint
);

-- ─── PLANS TABLE ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS plans (
  id text PRIMARY KEY,
  name text NOT NULL,
  price_monthly_cents int,
  price_yearly_cents int,
  max_filters int DEFAULT 1,
  max_resumes int DEFAULT 1,
  boolean_operators boolean DEFAULT false,
  sms_notifications boolean DEFAULT false,
  auto_apply boolean DEFAULT false,
  api_access boolean DEFAULT false,
  max_api_calls_daily int DEFAULT 0,
  network_intelligence boolean DEFAULT false,
  resume_grading boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

INSERT INTO plans (id, name, price_monthly_cents, price_yearly_cents, max_filters, max_resumes, boolean_operators, sms_notifications, auto_apply, api_access, max_api_calls_daily, network_intelligence, resume_grading) VALUES
  ('free', 'Free', 0, 0, 1, 1, false, false, false, false, 0, false, false),
  ('pro', 'Pro', 1999, 19990, 10, 5, true, true, true, false, 0, true, true),
  ('enterprise', 'Enterprise', 4999, 49990, 999, 99, true, true, true, true, 10000, true, true)
ON CONFLICT (id) DO NOTHING;

-- ─── SUBSCRIPTIONS TABLE ───────────────────────────────────
CREATE TABLE IF NOT EXISTS subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users ON DELETE CASCADE UNIQUE,
  plan_id text REFERENCES plans(id),
  stripe_customer_id text,
  stripe_subscription_id text,
  status text DEFAULT 'active' CHECK (status IN ('active', 'past_due', 'cancelled', 'trialing')),
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ─── AUDIT LOG TABLE ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users,
  action text NOT NULL,
  resource_type text,
  resource_id text,
  details jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamptz DEFAULT now()
);

-- ─── HELPER FUNCTIONS ──────────────────────────────────────
CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin');
$$;

CREATE OR REPLACE FUNCTION check_feature(p_feature text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id uuid;
  v_plan plans;
  v_count int;
  v_limit int;
  v_allowed boolean;
  v_reason text;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('allowed', false, 'reason', 'Not authenticated');
  END IF;

  SELECT p.* INTO v_plan FROM plans p
  JOIN subscriptions s ON s.plan_id = p.id
  WHERE s.user_id = v_user_id AND s.status IN ('active', 'trialing')
  LIMIT 1;

  IF NOT FOUND THEN
    SELECT p.* INTO v_plan FROM plans p
    JOIN profiles pr ON pr.plan = p.id
    WHERE pr.id = v_user_id;
  END IF;

  IF NOT FOUND THEN
    SELECT * INTO v_plan FROM plans WHERE id = 'free';
  END IF;

  CASE p_feature
    WHEN 'create_filter' THEN
      SELECT COALESCE(jsonb_array_length(user_data->'saved_filters'), 0) INTO v_count
      FROM profiles WHERE id = v_user_id;
      v_limit := v_plan.max_filters;
      v_allowed := v_count < v_limit;
      v_reason := CASE WHEN v_allowed THEN NULL ELSE 'Filter limit reached (' || v_count || '/' || v_limit || '). Upgrade for more.' END;
    WHEN 'upload_resume' THEN
      SELECT count(*) INTO v_count FROM resumes WHERE user_id = v_user_id;
      v_limit := v_plan.max_resumes;
      v_allowed := v_count < v_limit;
      v_reason := CASE WHEN v_allowed THEN NULL ELSE 'Resume limit reached (' || v_count || '/' || v_limit || '). Upgrade for more.' END;
    WHEN 'boolean_operators' THEN
      v_allowed := v_plan.boolean_operators;
      v_reason := CASE WHEN v_allowed THEN NULL ELSE 'Boolean operators require Pro plan' END;
    WHEN 'sms_notifications' THEN
      v_allowed := v_plan.sms_notifications;
      v_reason := CASE WHEN v_allowed THEN NULL ELSE 'SMS notifications require Pro plan' END;
    WHEN 'auto_apply' THEN
      v_allowed := v_plan.auto_apply;
      v_reason := CASE WHEN v_allowed THEN NULL ELSE 'Auto-apply requires Pro plan' END;
    WHEN 'api_access' THEN
      v_allowed := v_plan.api_access;
      v_reason := CASE WHEN v_allowed THEN NULL ELSE 'API access requires Enterprise plan' END;
    WHEN 'network_intelligence' THEN
      v_allowed := v_plan.network_intelligence;
      v_reason := CASE WHEN v_allowed THEN NULL ELSE 'Network intelligence requires Pro plan' END;
    WHEN 'resume_grading' THEN
      v_allowed := v_plan.resume_grading;
      v_reason := CASE WHEN v_allowed THEN NULL ELSE 'Resume grading requires Pro plan' END;
    ELSE
      v_allowed := false;
      v_reason := 'Unknown feature: ' || p_feature;
  END CASE;

  RETURN jsonb_build_object(
    'allowed', v_allowed,
    'plan', v_plan.id,
    'feature', p_feature,
    'reason', v_reason,
    'current', v_count,
    'limit', v_limit,
    'upgrade', NOT v_allowed
  );
END;
$$;

-- ─── INDEXES ───────────────────────────────────────────────
-- ats_jobs indexes
CREATE INDEX IF NOT EXISTS idx_ats_jobs_location_structured ON ats_jobs (loc_country, loc_state, loc_city) WHERE status = 'open';
CREATE INDEX IF NOT EXISTS idx_ats_jobs_source_status ON ats_jobs (ats_source, status);
CREATE INDEX IF NOT EXISTS idx_ats_jobs_status_updated ON ats_jobs (status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_ats_jobs_company_name ON ats_jobs (company_name);
CREATE INDEX IF NOT EXISTS idx_ats_jobs_slug_source_status ON ats_jobs (company_slug, ats_source, status);
CREATE INDEX IF NOT EXISTS idx_ats_jobs_first_seen_status ON ats_jobs (first_seen_at, status) WHERE status = 'open';
CREATE INDEX IF NOT EXISTS idx_ats_jobs_salary ON ats_jobs (salary_min, salary_max) WHERE salary_min IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ats_jobs_closed_at ON ats_jobs (closed_at) WHERE closed_at IS NOT NULL;

-- Other table indexes
CREATE INDEX IF NOT EXISTS idx_connections_user_company ON connections (user_id, parsed_company);
CREATE INDEX IF NOT EXISTS idx_resumes_user ON resumes (user_id);
CREATE INDEX IF NOT EXISTS idx_companies_refresh_active ON ats_companies (last_checked ASC NULLS FIRST, source) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_log_status ON notification_log (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON subscriptions (user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe ON subscriptions (stripe_customer_id) WHERE stripe_customer_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_profiles_plan ON profiles (plan);
CREATE INDEX IF NOT EXISTS idx_profiles_user_data_gin ON profiles USING GIN (user_data);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_log (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_log (action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_resource ON audit_log (resource_type, resource_id);

-- ─── SURVEY SOCIAL PROOF VIEW ──────────────────────────────
CREATE OR REPLACE VIEW survey_social_proof AS
SELECT
  COUNT(*) FILTER (WHERE survey_version LIKE 'periodic%' OR survey_version LIKE 'nps%') AS total_respondents,
  ROUND(AVG((answers->>'overall_rating')::numeric) FILTER (WHERE answers->>'overall_rating' IS NOT NULL), 1) AS avg_rating,
  ROUND(AVG(nps_score::numeric) FILTER (WHERE nps_score IS NOT NULL), 0) AS avg_nps,
  COUNT(*) FILTER (WHERE nps_score >= 9) AS promoters,
  COUNT(*) FILTER (WHERE nps_score >= 7 AND nps_score <= 8) AS passives,
  COUNT(*) FILTER (WHERE nps_score <= 6) AS detractors
FROM feedback
WHERE created_at > now() - interval '90 days';

GRANT SELECT ON survey_social_proof TO anon;
